In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import os
db_url = os.environ['DB_HEROKU']

In [3]:
#from base import Base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

In [4]:
print(db_url)

postgres://hiikokjjrwmqpg:ff6d83e0795990ffb048d526caf295eaad7a45476691991f989be513d4e3a6bb@ec2-54-83-60-13.compute-1.amazonaws.com:5432/d617hc9tos6o76

In [8]:
import sys
sys.path.append("/Users/szagar/ZTS/Dropbox/Business/ats/Code/Model/v2")

from market import Market
from strategy import Strategy
#from stress_test import StressTest
from market_internal import MarketInternal
from base import Base,Session

In [9]:
engine = create_engine(db_url)
Base.metadata.bind = engine

In [6]:
Base.metadata.create_all(bind=engine)

In [10]:
db = Session()

In [11]:
def marketsData():
    return db.query(Market.symbol,
                    Market.ts_symbol,
                    Market.name,
                    Market.default_session).all()

In [12]:
def getSecInfoBySymbol(sym):
    return db.query(Market).filter(Market.ts_symbol==sym).all()

In [13]:
import pandas as pd
df=pd.DataFrame(marketsData())
df

   symbol ts_symbol                  name  default_session
0     @ES     @ES.D         Emini S&P 500              9.0
1     @YM     @YM.D          Emini Dow 30              9.0
2     @NQ     @NQ.D          Emini NASDAQ              9.0
3    @RTY    @RTY.D         Emini Russell              9.0
4    @EMD    @EMD.D      Emini MidCap 400              9.0
5     @CL       @CL             Crude Oil              7.0
6     @NG       @NG           Natural Gas              7.0
7     @RB       @RB         RBOB Gasoline              7.0
8     @HO       @HO           Heating Oil              7.0
9     @GC       @GC                  Gold             10.0
10    @SI       @SI                Silver              3.0
11    @HG       @HG                Copper              2.0
12     @C        @C                  Corn              5.0
13     @S        @S              Soybeans              5.0
14    @ZW       @ZW                 Wheat              5.0
15    @LC       @LC           Live Cattle              6.0
16    @HE       @HE             Live Hogs              6.0
17    @ZM       @ZM          Soybean Meal              5.0
18    @ZL       @ZL           Soybean Oil              5.0
19  @CC-M     @CC-M                 Cocoa              0.0
20  @KC-M     @KC-M                Coffee              0.0
21  @SB-M     @SB-M                 Sugar              0.0
22  @CT-M     @CT-M                Cotton              0.0
23    @GE       @GE           Eurodollars              0.0
24    @ZB       @ZB         30 Year Bonds              0.0
25    @ZN       @ZN         10 Year Bonds              0.0
26    @ZF       @ZF          5 Year Notes              0.0
27    @ZT       @ZT          2 Year Notes              0.0
28    @ZQ       @ZQ             Fed Funds              0.0
29    @LH       @LH             Lean Hogs              NaN
30     @W        @W                 Wheat              NaN
31    @BO       @BO           Soybean Oil              NaN
32    @NK       @NK                Nikkei              NaN
33    @KW       @KW  Hard RD Winter Wheat              NaN

In [14]:
r=marketsData()

In [15]:
r2=pd.DataFrame(getSecInfoBySymbol('@ES.D'))
r2

InvalidRequestError: When initializing mapper Mapper|Strategy|strategies, expression 'OosTest' failed to locate a name ("name 'OosTest' is not defined"). If this is a class name, consider adding this relationship() to the <class 'strategy.Strategy'> class after both dependent classes have been defined.

In [23]:
print(*r2, sep='/n')

<Market(name='Emini S&P 500', symbol='@ES.D', group='Indices')>

In [27]:
print('\n'.join(str(p) for p in r2[0]))

<Market(name='Emini S&P 500', symbol='@ES.D', group='Indices')>

In [28]:
r2

                                                   0
0  <Market(name='Emini S&P 500', symbol='@ES.D', ...

In [29]:
r2[0]

0    <Market(name='Emini S&P 500', symbol='@ES.D', ...
Name: 0, dtype: object

In [30]:
float(r2[0].comm_entry_dol)

AttributeError: 'Series' object has no attribute 'comm_entry_dol'

In [31]:
a=float(comm)+8.5

NameError: name 'comm' is not defined

In [32]:
a

NameError: name 'a' is not defined

In [33]:
df

   symbol ts_symbol              name  default_session
0     @ES     @ES.D     Emini S&P 500                9
1     @YM     @YM.D      Emini Dow 30                9
2     @NQ     @NQ.D      Emini NASDAQ                9
3    @RTY    @RTY.D     Emini Russell                9
4    @EMD    @EMD.D  Emini MidCap 400                9
5     @CL       @CL         Crude Oil                7
6     @NG       @NG       Natural Gas                7
7     @RB       @RB     RBOB Gasoline                7
8     @HO       @HO       Heating Oil                7
9     @GC       @GC              Gold               10
10    @SI       @SI            Silver                3
11    @HG       @HG            Copper                2
12    @ZC       @ZC              Corn                5
13     @S        @S          Soybeans                5
14    @ZW       @ZW             Wheat                5
15    @LC       @LC       Live Cattle                6
16    @HE       @HE         Live Hogs                6
17    @ZM       @ZM      Soybean Meal                5
18    @ZL       @ZL       Soybean Oil                5
19  @CC-M     @CC-M             Cocoa                0
20  @KC-M     @KC-M            Coffee                0
21  @SB-M     @SB-M             Sugar                0
22  @CT-M     @CT-M            Cotton                0
23    @GE       @GE       Eurodollars                0
24    @ZB       @ZB     30 Year Bonds                0
25    @ZN       @ZN     10 Year Bonds                0
26    @ZF       @ZF      5 Year Notes                0
27    @ZT       @ZT      2 Year Notes                0
28    @ZQ       @ZQ         Fed Funds                0